### ISSUE TITLE
Is max_y typo or not?

### ISSUE THREAD

**Issue by renardelyon** [ghiffaryr/grplot#24]
https://github.com/ghiffaryr/grplot/blob/27c54f4704bb7537429cf56ca63e1cfc0d4cd1ce/grplot/features/text/text_def.py#L454

@ghiffaryr ini memang `max_y` atau typo harusnya `min_y`

**Comment by ghiffaryr** [comment]
harusnya typo itu, baru sadar juga. ginilah kalo ngoding sendiri wkwkwk. tar gua perbaiki sekalian update fitur filter. lagi chaos deadline sama belum sembuh total covid gua.

**Comment by renardelyon** [comment]
cepet sembuh lah, sama ini gw aja yang ganti gw lagi ngerefactor `text_def` jadi pake prinsip SOLID biar lebih scalable sma readable
