### ISSUE TITLE
Is `,c` typo?

### ISSUE THREAD

**Issue by renardelyon** [ghiffaryr/grplot#41]
https://github.com/ghiffaryr/grplot/blob/acf2edadc139d00eb021d88196274560ed20ec45/grplot/features/sep/statdesc_sep/statdesc_sep_def.py#L28-L29

@ghiffaryr ini typo harusnya `['.c', '.cL']` atau memang itu udah bener?

**Comment by ghiffaryr** [comment]
ah baru ketauan pas sekarang, pantesan biasanya langsung masuk ke pembulatan 5 angka belakang koma
