### ISSUE TITLE
@ghiffaryr ini gimana cara biar set_rotationnya ngasih error?

### ISSUE THREAD

**Issue by ghiffaryr** [ghiffaryr/grplot#7]
@ghiffaryr ini gimana cara biar set_rotationnya ngasih error?
```python
def rot_def(ax, axis, rot):
    if axis == 'x':
        try:
            for label in ax.get_xticklabels():
                label.set_rotation(rot)
        except:
            raise Exception('Unknown rot argument!')
    elif axis == 'y':
        try:
            for label in ax.get_yticklabels():
                label.set_rotation(rot)
        except:
            raise Exception('Unknown rot argument!')
    else:
        raise Exception('Unsupported axis!')
    return ax
```

_Originally posted by @renardelyon in https://github.com/ghiffaryr/grplot/issues/4#issuecomment-1130186598_

gua taunya itu bisa angka doang sih. mungkin selain itu bakalan error. belum nemu dokumentasi matplotlibnya.

**Comment by renardelyon** [comment]
@ghiffaryr  gw nyoba array kosong gk ngasih error, ngasi error klo manggil method get_rotation
